apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pingpong-app
  namespace: refactory-test
  labels:
    app:  pingpong
spec:
  selector:
    matchLabels:
      app: pingpong
  replicas: 2
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: sumarsono/pingpong:v1
        ports:
        - containerPort: 8080
