apiVersion: v1
kind: Service
metadata:
  name: pingpong-app
  namespace: refactory-test
  labels:
    app: pingpong
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: pingpong
